version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: postgres
    network_mode: bridge
    container_name: posty
    environment:
      POSTGRES_DB: superfluid
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    restart: unless-stopped
  # bot:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.bot
  #   # run bot_cron.sh script every minute
  #   command: npx hardhat run --network localhost ./scripts/bot.js
  #   depends_on:
  #     - postgres
  #   environment:
  #     - PGHOST=postgres
  #     - PGUSER=postgres
  #     - PGDATABASE=superfluid
  #     - PGPASSWORD=password
  #     - PGPORT=5432
  #   volumes:
  #     # Maps our current project directory `.` to
  #     # our working directory in the container
  #     - ./:/usr/src/app/
  #     # node_modules workaround for volumes
  #     # https://stackoverflow.com/a/32785014
  #     - /usr/src/app/node_modules
